### ISSUE TITLE
Add support for all available storage boxes with one check

### ISSUE THREAD

**Issue by martinseener** [Barzahlen/check_hetzner_storage_box#1]
Currently one has to create one check for each storage box. Please add support for multiple storage boxes so one check will alert if one or more storage boxes reaching the limits

**Comment by wernerfred** [comment]
You can achieve this with icinga internal functions like it is done by the disk check with different partitions for example.

In my eyes, this would be the cleaner solution but that's kind of everyones philosophy.

**Comment by martinseener** [comment]
Hi @wernerfred,
from my understanding you can only use check_disk if the storage box is somehow (samba/nfs/sshfs) mounted on a local machine that has the check running. For our cases we don't have this setup but we only send data to the box without mounting it somewhere. Therefore i developed this plugin, so you still can monitor it without any further setup through the Hetzner Robot Webservice/API. I also want to develop it further than only checking storage box free space in the future.

If i'm wrong and there is another solution with Icinga2 built-in's, please tell me.

**Comment by wernerfred** [comment]
Sry i think we are not talking about the same thing, maybe my expressions were a bit confusing. I would suggest to do multiple checks with ur plugin not inside the script but with icinga internals like the default disk check is done (not acutally using the disk check, only the pattern)

So let me show you a example:
in my icinga2 instance i'm monitoring a server with multiple partitions and multiple apache vhosts whose certs i want to check . Now i can either use scripts which will check all given partitions or vhosts (resulting in one check for all, bad for runtime and emergency escalation) or i can use the standard disk check or the ssl cert check and define it like follows:

```
apply Service for (https_domain => config in host.vars.https_domains) {
  import "generic-service"
  check_command = "check_ssl_cert"
  vars.w_cert = "10"
  vars.c_cert = "5"
  vars += config
}
```
and in the host:
```
 vars.https_domains["cert phi"] = {
    https_domain = "phi.*******.**"
 }
```
This way everytime a new cert/partition/storage box is added you can simply extent the definition in the host which will result in a single, seperate check for each cert/storagebox/etc...

With this way you can also define seperate variables/warning and critical thresholds per box (10% of 25GB isn't 10% of 100Gb right? and not every box might have the same login credentials)

In my opinion this is the much cleaner way bc i think you would like to be notified in WHICH storage box a problem is occuring.

Let me know if i can help you anyway ;) Hope this was more understanding than the previous

**Comment by martinseener** [comment]
Ahh now i got it. You're totally right and i also thought about this in my first version if i want to check all boxes at once or not and so my first version only checks one at a time (which i think is the right way).

So yeah, i WILL NOT remove the possibility to check one box at a time with this check but i rather want to include another feature (command line flag) to add the possibility for people to check all at once, if they want to. The default will stay like it is currently (`-s box_id`) and i'll maybe introduce `-a` as an option to check `all` boxes at once for systems other than Icinga2 that don't support this kind of test separation.

I'll def. continue to maintain this check as we're also using it heavily. Thanks for helping out and commenting on it!

**Comment by martinseener** [comment]
I decided to close this issue after all. We also only have different storage box sizes and checking them all within one check run doesn't make sense and the code change necessary to add this ability would make the check thicker and less readable. So it will stay as is but i refactored a bit of the code since and added more exception handling stuff to be more robust
