### ISSUE TITLE
checkmk: Service Graph is broken

### ISSUE THREAD

**Issue by jkirk** [Barzahlen/check_hetzner_storage_box#7]
We use this monitoring check in our checkmk monitoring infrastructure via [MRPE](https://checkmk.com/integrations/mrpe).
This works quite fine, but we noticed that the Service Graph is missing / broken:

![image](https://user-images.githubusercontent.com/288637/134159749-4155a046-66fc-473e-a28c-0b2d07752a30.png)

_Manual transcription_:
```
ERROR: `Traceback` is not a valid function name in Traceback
[...]
/omd/sites/synpros/bin/rrdtool graph [...] Traceback (most recent call last): File "/omd/sites/synpros/lib/python/cmk/gui/metrics.py", line 688, in page_pnp_template
```

![image2](https://user-images.githubusercontent.com/288637/134159759-647cfc77-6389-4db1-b0b9-49b074a1cb0d.png)

_Manual transcription_:
```
ERROR: `File` is not a valid function name in File
[...]
/omd/sites/synpros/bin/rrdtool graph [...] Traceback (most recent call last): File "/omd/sites/synpros/lib/python/cmk/gui/metrics.py", line 742, in render_graph_pnp
```

Any idea what the problem could be or how to debug this problem further?

Thanks for your work!

**Comment by martinseener** [comment]
Hi @jkirk,
at first, thanks for reporting back a potential issue with us. We use this plugin with Icinga2 and currently don't see this issue (see attached screenshot:
![hsb1](https://user-images.githubusercontent.com/1584417/134166009-ab6b9333-d6d3-46d6-9634-619cfd58f8ed.png)

Nevertheless, I also checked the referenced commit. So I guess this fix works for you. I would rather change the label further to "Usage" (uppercase U), so it still makes sense and we can omit the "storagebox_" part here - obviously.
So I would rename it for the next version of the check and also test it with Icinga2 and you probably again with check_mk, so we can ensure it works for everyone else too. Are you in, trying this?

**Comment by jkirk** [comment]
Perfect. Thank you!
